### ISSUE TITLE
KeyError: 'occupation'

### ISSUE THREAD

**Issue by DrorDvash** [initstring/linkedin2username#69]
The script has done few loops and got 292 results out of 392 employees, and than failed with this error

Python 3.10.12

```
[*] Hopefully that's the right XXX! If not, check LinkedIn and try again.

[*] Calculating inner and outer loops...
[*] Company has 392 profiles to check. Some may be anonymous.
[*] Setting each iteration to a maximum of 16 loops of 25 results each.

[*] Starting search.... Press Ctrl-C to break and write files early.

[*] Scraping results on loop 15...    Traceback (most recent call last):g total: 292              
  File "/home/server/Tools/linkedin2username/linkedin2username.py", line 694, in <module>
    main()
  File "/home/server/Tools/linkedin2username/linkedin2username.py", line 684, in main
    employees = do_loops(session, company_id, outer_loops, args)
  File "/home/server/Tools/linkedin2username/linkedin2username.py", line 573, in do_loops
    found_employees = find_employees(result.text)
  File "/home/server/Tools/linkedin2username/linkedin2username.py", line 508, in find_employees
    'occupation': profile['occupation']}
KeyError: 'occupation'
```

**Comment by initstring** [comment]
Hi @DrorDvash - thanks for opening this!

Can you see if the branch https://github.com/initstring/linkedin2username/tree/69-keyerror-occupation fixes this problem? Just clone that branch and try it out.
